//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package anomaly

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerMetricsWithAnomaly) DeepCopyInto(out *ContainerMetricsWithAnomaly) {
	*out = *in
	in.ContainerMetrics.DeepCopyInto(&out.ContainerMetrics)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerMetricsWithAnomaly.
func (in *ContainerMetricsWithAnomaly) DeepCopy() *ContainerMetricsWithAnomaly {
	if in == nil {
		return nil
	}
	out := new(ContainerMetricsWithAnomaly)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodMetricsWithAnomaly) DeepCopyInto(out *PodMetricsWithAnomaly) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Timestamp.DeepCopyInto(&out.Timestamp)
	out.Window = in.Window
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]ContainerMetricsWithAnomaly, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodMetricsWithAnomaly.
func (in *PodMetricsWithAnomaly) DeepCopy() *PodMetricsWithAnomaly {
	if in == nil {
		return nil
	}
	out := new(PodMetricsWithAnomaly)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodMetricsWithAnomaly) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodMetricsWithAnomalyList) DeepCopyInto(out *PodMetricsWithAnomalyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodMetricsWithAnomaly, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodMetricsWithAnomalyList.
func (in *PodMetricsWithAnomalyList) DeepCopy() *PodMetricsWithAnomalyList {
	if in == nil {
		return nil
	}
	out := new(PodMetricsWithAnomalyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodMetricsWithAnomalyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
